# Generated by Django 3.1.4 on 2021-01-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailymeal', '0004_auto_20210119_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailymeal',
            old_name='meals',
            new_name='mealList',
        ),
    ]
