# Generated by Django 3.1.4 on 2021-01-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailymeal', '0006_auto_20210119_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='bitmap',
            field=models.TextField(default=''),
        ),
    ]
