# Generated by Django 3.1.4 on 2021-01-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customhb', '0005_customhabit_iconid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customhabit',
            name='isVisible',
            field=models.IntegerField(default=0),
        ),
    ]
