# Generated by Django 3.1.4 on 2021-01-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customhb', '0007_customhabit_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customhabit',
            old_name='updated',
            new_name='CHupdated',
        ),
    ]
