# Generated by Django 3.1.4 on 2020-12-26 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0002_auto_20201226_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='runningtime',
            new_name='runningTime',
        ),
    ]
