# Generated by Django 3.1.4 on 2021-01-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0004_auto_20201226_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='isVisible',
            field=models.IntegerField(default=0),
        ),
    ]
