# Generated by Django 3.1.4 on 2021-01-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailycthb', '0003_auto_20201226_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycustomhabit',
            name='isVisible',
            field=models.IntegerField(default=0),
        ),
    ]
