# Generated by Django 3.1.4 on 2020-12-26 05:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sleep', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sleep',
            old_name='endtime',
            new_name='endTimeMilli',
        ),
        migrations.RenameField(
            model_name='sleep',
            old_name='quality',
            new_name='sleepQuality',
        ),
        migrations.RenameField(
            model_name='sleep',
            old_name='starttime',
            new_name='startTimeMilli',
        ),
        migrations.AlterUniqueTogether(
            name='sleep',
            unique_together={('user', 'startTimeMilli')},
        ),
    ]
