# Generated by Django 3.1.4 on 2021-01-18 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_auto_20201229_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenbenh', models.CharField(max_length=100)),
                ('thoigiandieutri', models.IntegerField()),
                ('bacsiquanly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_bsql', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_bn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benhvien', models.CharField(max_length=100)),
                ('chuyennganh', models.CharField(max_length=100)),
                ('sonamcongtac', models.IntegerField()),
                ('trinhdo', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
