# Generated by Django 3.1.4 on 2021-01-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0004_auto_20210118_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='diachi',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='tuoi',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
