# Generated by Django 3.1.4 on 2021-01-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0008_auto_20210119_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='tenbenh',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='thoigiandieutri',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
