# Generated by Django 3.1.4 on 2021-01-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0009_auto_20210119_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
