# Generated by Django 3.1.4 on 2021-01-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0011_myuser_gioitinh'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='ngaysinh',
            field=models.CharField(default='', max_length=20),
        ),
    ]
