# Generated by Django 3.1.4 on 2021-01-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0012_myuser_ngaysinh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=15, unique=True)),
                ('visiRun', models.IntegerField(default=0)),
                ('visiSleep', models.IntegerField(default=0)),
                ('visiMeal', models.IntegerField(default=0)),
            ],
        ),
    ]
