# Generated by Django 3.1.4 on 2021-01-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0010_auto_20210120_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='gioitinh',
            field=models.IntegerField(default='0'),
        ),
    ]
