# Generated by Django 3.1.4 on 2021-01-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0013_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.TextField(default=''),
        ),
    ]
