# Generated by Django 3.1.4 on 2021-01-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0002_auto_20210119_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='updated',
            field=models.IntegerField(default=1),
        ),
    ]
