# Generated by Django 3.1.4 on 2020-12-26 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='route',
            new_name='routeID',
        ),
    ]
