# Generated by Django 3.1.4 on 2021-01-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailymeal', '0003_auto_20201230_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitmap', models.CharField(default='', max_length=200)),
                ('calories', models.IntegerField(default=0, max_length=10)),
                ('name', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='dailymeal',
            name='calo',
        ),
        migrations.AlterField(
            model_name='dailymeal',
            name='target',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='dailymeal',
            name='meals',
            field=models.ManyToManyField(to='dailymeal.Meal'),
        ),
    ]
