# Generated by Django 3.1.4 on 2021-01-19 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailymeal', '0005_auto_20210119_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymeal',
            name='mealList',
        ),
        migrations.AddField(
            model_name='meal',
            name='dailymeal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mealList', to='dailymeal.dailymeal'),
        ),
    ]
