# Generated by Django 3.1.4 on 2021-01-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailymeal', '0007_auto_20210119_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymeal',
            name='isVisible',
            field=models.IntegerField(default=0),
        ),
    ]
