# Generated by Django 3.1.4 on 2020-12-28 00:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customhb', '0003_auto_20201226_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='customhabit',
            name='HabitID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='customhabit',
            unique_together={('HabitID', 'user')},
        ),
        migrations.RemoveField(
            model_name='customhabit',
            name='habitID',
        ),
    ]
