# Generated by Django 3.1.4 on 2021-01-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customhb', '0004_auto_20201228_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='customhabit',
            name='iconID',
            field=models.CharField(default='', max_length=20),
        ),
    ]
